name: Deploy Web

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - scripts/**
      - src/common/**
      - src/web/**

env:
  REMOTE_DIR: /var/www/wowpay2win.com
  WEB_DIR: dist-web
  CRON_DIR: dist-cron
  CACHE_DIR: src/web/assets/data
  IMAGE_DIR: src/web/assets/img/items

jobs:
  deployProduction:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Create SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('**/yarn.lock', '**/package-lock.json') }}

      - name: Cache API Data
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-api-data
        with:
          path: |
            ${{ env.CACHE_DIR }}
            ${{ env.IMAGE_DIR }}
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('src/cron/**/*.ts', 'src/common/**/*.ts') }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Cron
        run: yarn buildCron

      - name: Run fetchData
        run: yarn fetchData
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - name: Build Web
        run: yarn buildWeb

      - name: Deploy Frontend to Server
        run: |
          ssh -o StrictHostKeyChecking=no -o SendEnv=REMOTE_DIR -o SendEnv=WEB_DIR "$SSH_USER@$SSH_HOST" "find $REMOTE_DIR/$WEB_DIR -type f -not -path */data/* | xargs -t rm -f"
          rsync -e "ssh -o StrictHostKeyChecking=no" -r "$WEB_DIR"  "$SSH_USER@$SSH_HOST:$REMOTE_DIR"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
