name: Deploy Cron

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - src/common/**
      - src/cron/**

env:
  REMOTE_DIR: /var/www/wowpay2win.com
  WEB_DIR: dist-web
  CRON_DIR: dist-cron
  CACHE_DIR: src/web/assets/data
  IMAGE_DIR: src/web/assets/img/items

jobs:
  deployProduction:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Create SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Compile Cron on Server
        run: |
          ssh -o StrictHostKeyChecking=no -o SendEnv=REMOTE_DIR "$SSH_USER@$SSH_HOST" "cd $REMOTE_DIR && git pull --rebase origin master"
          ssh -o StrictHostKeyChecking=no -o SendEnv=REMOTE_DIR "$SSH_USER@$SSH_HOST" "cd $REMOTE_DIR && yarn buildCron"
          ssh -o StrictHostKeyChecking=no -o SendEnv=REMOTE_DIR "$SSH_USER@$SSH_HOST" "cd $REMOTE_DIR && yarn fetchData"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
